#!/usr/bin/env bash
set -euo pipefail

R=$(cd "$(dirname "$0")" && pwd)
O=${O:-$R/build/$ARCH}
CFLAGS=${CFLAGS:-}
THREADS=${THREADS:-}

mkdir -p "$O"
mkdir -p "$R/zig-cache"

CORE=$(tr -s '[:space:]' ' ' < "$R/core.cflags" | sed 's/^ //;s/ $//')
if [ "$THREADS" = "enabled" ]; then
    CFLAGS="${CFLAGS:+$CFLAGS }-matomics"
fi

cat <<NINJA
# Generated by build.sh — do not edit by hand
# To regenerate: ARCH='$ARCH' CC='$CC' AR='$AR' O='$O' CFLAGS='$CFLAGS' THREADS='$THREADS' $R/build.sh
ninja_required_version = 1.3

builddir = $O
cc_cmd   = $CC
ar_cmd   = $AR
cc_flags = -target $ARCH-freestanding $CORE${CFLAGS:+ $CFLAGS}
inc      = -isystem $R/source/include

rule cc
  command = \$cc_cmd \$cc_flags \$inc -c -o \$out \$in -MD -MF \$out.d
  depfile = \$out.d
  deps    = gcc
  description = CC \$out

rule ar
  command = rm -f \$out && \$ar_cmd -rcD \$out \$in
  description = AR \$out

rule regen
  command = ARCH='$ARCH' CC='$CC' AR='$AR' O='$O' CFLAGS='$CFLAGS' THREADS='$THREADS' '$R/build.sh' > \$out
  generator = 1
  description = Regenerating build.ninja

build build.ninja: regen $R/build.sh $R/core.cflags

build $O/setjmp_core.o: cc $R/source/lib/setjmp_core_$ARCH.S
build $O/mman.o:        cc $R/source/lib/mman.c
build $O/setjmp.o:      cc $R/source/lib/setjmp.c
build $O/dlmalloc.o:    cc $R/source/dlmalloc/src/dlmalloc.c

build $O/libcorkel.a: ar $O/dlmalloc.o $O/setjmp_core.o $O/setjmp.o $O/mman.o

default $O/libcorkel.a
NINJA
